"""Repo + capability Protocols. Stdlib only."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Clock(Protocol):
    def now_ms(self) -> int: ...


@runtime_checkable
class IdGen(Protocol):
    def new_id(self) -> str: ...


@runtime_checkable
class Embedder(Protocol):
    def embed(self, text: str) -> list[float]: ...


@runtime_checkable
class Notifier(Protocol):
    def publish(self, topic: str, message: str) -> None: ...


@runtime_checkable
class SearchBackend(Protocol):
    def search(self, query: str, limit: int = 10) -> list[Any]: ...


@runtime_checkable
class NodeRepo(Protocol):
    def create_node(self, node: Any) -> Any: ...
    def get_node(self, node_id: str) -> Any | None: ...
    def update_node(self, node: Any) -> Any: ...
    def delete_node(self, node_id: str) -> None: ...
    def list_children(self, parent_id: str | None) -> list[Any]: ...


@runtime_checkable
class EventRepo(Protocol):
    def create_event(self, event: Any) -> Any: ...
    def get_event(self, event_id: str) -> Any | None: ...
    def update_event(self, event: Any) -> Any: ...
    def delete_event(self, event_id: str) -> None: ...
    def events_in_window(self, from_ms: int, to_ms: int) -> list[Any]: ...


@runtime_checkable
class BucketRepo(Protocol):
    def get_bucket(self, bucket_id: str) -> Any | None: ...
    def buckets_by_level(self, level: str) -> list[Any]: ...


@runtime_checkable
class SeriesRepo(Protocol):
    def create_series(self, series: Any) -> Any: ...
    def get_series(self, series_id: str) -> Any | None: ...
    def delete_series(self, series_id: str) -> None: ...


@runtime_checkable
class ScheduleRepo(Protocol):
    def create_schedule(self, schedule: Any) -> Any: ...
    def get_schedule(self, schedule_id: str) -> Any | None: ...
    def update_schedule(self, schedule: Any) -> Any: ...
    def list_schedules(self) -> list[Any]: ...


@runtime_checkable
class ReminderRepo(Protocol):
    def create_reminder(self, reminder: Any) -> Any: ...
    def due_reminders(self, now_ms: int) -> list[Any]: ...
    def mark_sent(self, reminder_id: str) -> None: ...


@runtime_checkable
class TimerRepo(Protocol):
    def start_timer(self, session: Any) -> Any: ...
    def stop_timer(self, timer_id: str, ended_at: int) -> Any: ...
    def running_timer(self) -> Any | None: ...


@runtime_checkable
class AuditStore(Protocol):
    def append(self, entry: Any) -> Any: ...
    def recent(self, limit: int = 100) -> list[Any]: ...
